
public class Test {

	public static void main(String[] args) {
		String sql = "select c.sheet_id,b.product_code,c.e8c,c.e8c_type,c.iomcomments,"
				+ " (select a.object_desc from  cnst_kt_res_nbr_info a where a.type_id = 1  and a.param_id = d.id and rownum=1) DHHM1,"
				+ " (select (case when x.operaflag = '0' then l.oldcharactevaluename else l.charactevaluename end) charactevaluename"
				+ "   from cnst_kt_prodorderattr  l,cnst_kt_server_order   x,cnst_kt_indepprodorder p"
				+ "    where p.id = l.charactercode and l.characterid = '9' and x.sheet_id = c.sheet_id and x.sheet_id = p.sheet_id and rownum = 1) DHHM2,"
				+ " (select b.object_desc from  cnst_kt_res_obj_info b where b.type_id = 165 and b.param_id = d.id and rownum=1) BDHM,"
				+ " (select v.EXCHANGE from  cnst_kt_orders_view v where v.Sheet_Id = c.sheet_id and rownum=1) JZDM,"
				+ " (select v.EXCHANGE_NAME from  cnst_kt_orders_view v where v.Sheet_Id = c.sheet_id and rownum=1) JZMC,"
				+ " (select b.object_desc from  cnst_kt_res_obj_info b where b.type_id = 102 and b.param_id = d.id and rownum=1) JJXH,"
				+ " (select m.object_desc from  cnst_kt_mdf_view m where m.orientation = '2' and m.param_id = d.id and rownum=1) ZLKD,"
				+ " (select bv.object_desc from  cnst_kt_box_view bv where bv.orientation = '1' and bv.param_id = d.id and rownum=1) ZGXX1,"
				+ " (select mv.object_desc from  cnst_kt_obj_main mv where mv.type_id = 103 and mv.param_id = d.id and rownum=1) ZGXX2,"
				+ " (select sv.object_desc from  cnst_kt_obj_second sv where sv.type_id = 103 and sv.param_id = d.id and rownum=1) PXXX1,"
				+ " (select pv.object_desc from  cnst_kt_fen_box_view pv where pv.type_id = 103 and pv.param_id = d.id and rownum=1) PXXX2,"
				+ " (select b.object_desc from  cnst_kt_res_obj_info b where b.type_id = 101 and b.param_id = d.id and rownum=1) FXXH,"
				+ " (select sv.object_desc from  cnst_kt_obj_second sv where sv.type_id = 0 and sv.param_id = d.id and rownum=1) FXXXX,"
				+ " (select m.object_desc from  cnst_kt_mdf_view m where m.orientation = '1' and m.param_id = d.id and rownum=1) HLKD,"
				+ " (select n.object_desc from  cnst_kt_res_nbr_info n where n.type_id = 9 and n.param_id = d.id and rownum=1) WLHM,"
				+ " (select b.object_desc from  cnst_kt_res_obj_info b where b.type_id = 107 and b.param_id = d.id and rownum=1) YYDK,"
				+ " (select o.orientation from  cnst_kt_res_obj_info o where o.type_id = 106 and o.param_id = d.id and rownum=1) YYSB,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 108 and o.param_id = d.id and rownum=1) DSLAMXL,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 110 and o.param_id = d.id and rownum=1) DSLAMJH,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 109 and o.param_id = d.id and rownum=1) DSLAMDK,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 212 and o.param_id = d.id and rownum=1) GJBM,"
				+ " (select o.object_id from  cnst_kt_res_obj_info o where o.type_id = 212 and o.param_id = d.id and rownum=1) GJMC,"
				+ " (select o.orientation from  cnst_kt_res_obj_info o where o.type_id = 212 and o.param_id = d.id and rownum=1) GJDK,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 213 and o.param_id = d.id and rownum=1) GFBM,"
				+ " (select o.object_id from  cnst_kt_res_obj_info o where o.type_id = 213 and o.param_id = d.id and rownum=1) GFMC,"
				+ " (select o.orientation from  cnst_kt_res_obj_info o where o.type_id = 213 and o.param_id = d.id and rownum=1) GFDK,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 214 and o.param_id = d.id and rownum=1) TWOOBDBM,"
				+ " (select o.orientation from  cnst_kt_res_obj_info o where o.type_id = 214 and o.param_id = d.id and rownum=1) TWOOBDDK,"
				+ " (select o.object_desc from  cnst_kt_res_obj_info o where o.type_id = 122 and o.param_id = d.id and rownum=1) ONEOBDBM,"
				+ " (select o.ORIENTATION from  cnst_kt_res_obj_info o where o.type_id = 119 and o.param_id = d.id and rownum=1) OLT_PORT,"
				+ " (select o.OTHER_ATTR from  cnst_kt_res_obj_info o where o.type_id = 119 and o.param_id = d.id and rownum=1) OLT_NAME,"
				+ " (select o.CIRCUIT_CODE from cnst_kt_res_obj_info o where o.type_id=000  and o.physic_textroute is not null and o.param_id=d.Id and rownum=1) CIRCUIT_CODE,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='3106' and i.sheet_id=c.sheet_id and rownum=1) LOID,"
				+ " (select r.object_desc from tssa.cnst_kt_lan_res_view r where r.param_id = d.id and rownum=1) ZYMS,"
				+ " (select k.charactevaluename from cnst_kt_prodorderattr k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '13' and i.sheet_id = c.sheet_id and rownum = 1) SBLY,"
				+ " (select k.charactevaluename from cnst_kt_prodorderattr k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '182269' and i.sheet_id = c.sheet_id and rownum = 1) KDSBLX,"
				+ " (select n3.charactervalue from CNST_KT_DEPENDPRODORDER d, CNST_KT_ProdOrderAttr_Ext n3 where n3.charactercode = d.id and n3.characterid = '182270' and d.dependprodid = '236947' and d.sheet_id = c.sheet_id and rownum = 1) FWBZ,"
				+ " (select D.DEPENDPRODNAME from CNST_KT_DEPENDPRODORDER d where d.dependprodid in ( '237647','237648','237649','237650','237651','237652','237653','237687','237688','237689','237690','237691','237692','237693','237694','237695','237707','237708','237709','237776','237777','237778','237779','237780','237781','237782','237783','237784','237785') and d.sheet_id = c.sheet_id and rownum = 1) KD_FSCP,"
				+ " (select D.DEPENDPRODNAME from CNST_KT_DEPENDPRODORDER d where d.dependprodid = '237633' and d.sheet_id = c.sheet_id and rownum = 1) ITV_FSCP,"
				+ " (select decode(n3.charactervalue,1,'用户自备',2,'租用局方',3,'协议租机') from CNST_KT_DEPENDPRODORDER d, cnst_kt_prodorderattr_Ext n3 where n3.charactercode = d.id and n3.characterid = '182395' and d.dependprodid = '237633' and d.sheet_id = c.sheet_id and rownum = 1) XJ_SXTLY, "
				+ " (select decode(n3.charactervalue,1,'标清','2','高清') from CNST_KT_DEPENDPRODORDER d, cnst_kt_prodorderattr_Ext n3 where n3.charactercode = d.id and n3.characterid = '182396' and d.dependprodid = '237633' and d.sheet_id = c.sheet_id and rownum = 1) XJ_SXTLX,"
				+ " (select n3.charactervalue from CNST_KT_DEPENDPRODORDER d, cnst_kt_prodorderattr_Ext n3 where n3.charactercode = d.id and n3.characterid = '182397' and d.dependprodid = '237633' and d.sheet_id = c.sheet_id and rownum = 1) XJ_SXTXH,"
				+ " (select k.oldcharactevaluename from cnst_kt_prodorderattr k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '13' and i.sheet_id = c.sheet_id and rownum = 1) OLDSBLY,"
				+ " (select bn.businname from cnst_kt_prodorderattr k, cnst_kt_indepprodorder i,bndict_t_dictionary bn where k.charactercode = i.id and k.characterid in ('3105','3761') and i.sheet_id = c.sheet_id and bn.busintypeid = 'E8_C_TYPE' and bn.businid = k.charactervalue and rownum = 1) || (SELECT '(' || k2.type_desc || ')' FROM cnst_kt_res_obj_info k2  WHERE k2.param_id = d.ID  AND k2.type_id = 156 AND ROWNUM = 1)  JRFS,"
				+ " (select bn.businname from cnst_kt_prodorderattr k, cnst_kt_indepprodorder i,bndict_t_dictionary bn where k.charactercode = i.id and k.characterid in ('3105','3761') and i.sheet_id = c.sheet_id and bn.busintypeid = 'E8_C_TYPE' and bn.businid = k.oldcharactervalue and rownum = 1) OLDJRFS,"
				+ " (select k.charactevaluename from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='125' and i.sheet_id=c.sheet_id and rownum=1) KDZH,"
				+ " (select k.charactevaluename from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='126' and i.sheet_id=c.sheet_id and rownum=1) KDMM,"
				+ " (select k.charactevaluename from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='123' and i.sheet_id=c.sheet_id and rownum=1) KDSL,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='519' and i.sheet_id=c.sheet_id and rownum=1) ITVZH,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='3566' and i.sheet_id=c.sheet_id and rownum=1) ITVMM,"
				+ " (select bn1.businname NEW_IPTV_TYPE   from cnst_kt_prodorderattr  k, cnst_kt_indepprodorder i,  bndict_t_dictionary    bn1 where k.charactercode = i.id and k.characterid = '517' and i.sheet_id = c.sheet_id and bn1.busintypeid = 'IPTV_TYPE'  and bn1.status = '0'  and  bn1.businid = k.charactervalue and rownum=1)  NEW_IPTV_TYPE, "
				+ " (select bn2.businname OLD_IPTV_TYPE   from cnst_kt_prodorderattr  k, cnst_kt_indepprodorder i,  bndict_t_dictionary    bn2 where k.charactercode = i.id and k.characterid = '517' and i.sheet_id = c.sheet_id and bn2.busintypeid = 'IPTV_TYPE'  and bn2.status = '0'  and  bn2.businid =  k.oldcharactervalue and rownum=1)   OLD_IPTV_TYPE , "
				+ " (select k.charactevaluename from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='42' and i.sheet_id=c.sheet_id and rownum=1) FZR,"
				+ " (select k.charactevaluename from Cnst_Kt_Prodorderattr_View k,cnst_kt_indepprodorder i where k.charactercode=i.id and k.characterid='230' and i.sheet_id=c.sheet_id and rownum=1) FZDW,"
				+ " (select sv.object_desc from  cnst_kt_obj_main sv where sv.type_id = 0 and sv.param_id = d.id and rownum=1) PXXXZ,  "
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '2127' and i.sheet_id = c.sheet_id and rownum = 1) SIMC,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '181851' and i.sheet_id = c.sheet_id and rownum = 1) SXTLX,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '766' and i.sheet_id = c.sheet_id and rownum = 1) CZZH,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '181854' and i.sheet_id = c.sheet_id and rownum = 1) SXTDZ,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '9' and i.sheet_id = c.sheet_id and rownum = 1) IMSI ,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '8760' and i.sheet_id = c.sheet_id and rownum = 1) HLWDSLX,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '8762' and i.sheet_id = c.sheet_id and rownum = 1) HLWDSZH,"
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '8766' and i.sheet_id = c.sheet_id and rownum = 1) JDHCM,"
				+ " (select k.charactevaluename from CNST_BOOK_SERVICE_ORDERS   b, cnst_kt_server_order       cc, Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder     i "
				+ " where k.charactercode = i.id and k.characterid = '5171' and i.sheet_id = cc.sheet_id and cc.ordercodeid = b.id and b.product_code = '408' and b.service_order_id = a.book_id and rownum = 1) as iptv_fenzu, "
				+ " (select k.charactevaluename from CNST_BOOK_SERVICE_ORDERS   b, cnst_kt_server_order       cc, Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder     i "
				+ " where k.charactercode = i.id and k.characterid = '5172' and i.sheet_id = cc.sheet_id and cc.ordercodeid = b.id and b.product_code = '408' and b.service_order_id = a.book_id and rownum = 1) as iptv_pingtai, "
				+ " (select c2.charactervalue from CNST_KT_DEPENDPRODORDER c1,CNST_KT_PRODORDERATTR_EXT c2 where c1.sheet_id=c.sheet_id and c1.id=c2.charactercode and c2.charactername='有线VPDN拨号帐号') as VPDNBHZH, "
				+ " (select c2.charactervalue from CNST_KT_DEPENDPRODORDER c1,CNST_KT_PRODORDERATTR_EXT c2 where c1.sheet_id=c.sheet_id and c1.id=c2.charactercode and c2.charactername='拨号密码') as VPDNBHMM, "
				+ " (select k.charactervalue from Cnst_Kt_Prodorderattr_View k, cnst_kt_indepprodorder i where k.charactercode = i.id and k.characterid = '8761' and i.sheet_id = c.sheet_id and rownum = 1) HLWDSXH "
				+ "  from  cnst_build_sheet a,cnst_book_service_orders b, cnst_kt_server_order     c, cnst_kt_res_param        d "
				+ "  where  b.id = c.ordercodeid and d.sheet_id = c.sheet_id and b.service_order_id = a.book_id  and a.is_finished = 0   "
				+ " and a.processinstid = ? order by b.product_code desc";
		System.out.println(sql);

	}

}
